### ISSUE TITLE
Consider enabling this for non-IDEA IDEs

### ISSUE THREAD

**Issue by dlsniper** [novotnyr/consul-intellij-plugin#6]
Hi,

First of all, thank you for your work, I love it.
I would also like to ask you if you could please consider enabling this plugin for non-IDEA IDEs?
Is there any help that you need in order to do so?
Thank you.

**Comment by novotnyr** [comment]
This is a good idea. I was under impression that this is automatically compatible for other products. If you can point me to any specifics how to enable this, I would integrate it.

**Comment by novotnyr** [comment]
Fixed in v0.6
